export { default as PostCard } from './blog/PostCard';
export { default as Categories } from './blog/Categories';
export { default as PostWidget } from './blog/PostWidget';
// export { default as Header } from './blog/Header';
// export { default as Layout } from './blog/Layout';
// export { default as Author } from './blog/Author';
// export { default as CommentsForm } from './blog/CommentsForm';
// export { default as Comments } from './blog/Comments';
export { default as PostDetail } from './blog/PostDetail';
// export { default as FeaturedPostCard } from './blog/FeaturedPostCard';
// export { default as AdjacentPostCard } from './blog/AdjacentPostCard';
// export { default as Loader } from './blog/Loader';

// export { default as Hero } from './portfolio/Hero';
// export { default as Computers } from './portfolio/canvas/Computers';
// export { default as ComputerCanvas } from './portfolio/canvas/ComputerCanvas';
// export { default as CanvasLoader } from './portfolio/canvas/CanvasLoader';
// export { default as BallCanvas } from './portfolio/canvas/BallCanvas';
// export { default as Ball } from './portfolio/canvas/Ball';
// export { default as EarthCanvas } from './portfolio/canvas/EarthCanvas';
// export { default as StarsCanvas } from './portfolio/canvas/StarsCanvas';
// export { default as About } from './portfolio/About';
// export { default as Tech } from './portfolio/Tech';
// export { default as Experience } from './portfolio/Experience';
// export { default as Works } from './portfolio/Works';
// export { default as Contact } from './portfolio/Contact';